server:
  port: 5678
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dbsimplesales
    username: root
    password: admin1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    serialization:
      indent-output: true
